---
name: Build container images

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-images:
    name: ${{ matrix.image_name }} (${{ matrix.platform }})
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: dpu-sim-control-plane
            image_target: dpu-sim-control-plane
            platform: amd64
          - image_name: dpu-sim-control-plane
            image_target: dpu-sim-control-plane
            platform: arm64
          - image_name: dpu-sim-worker
            image_target: dpu-sim-worker
            platform: amd64
          - image_name: dpu-sim-worker
            image_target: dpu-sim-worker
            platform: arm64
    uses: ./.github/workflows/reusable-build-image.yml
    with:
      image-name: ${{ matrix.image_name }}
      image-target: ${{ matrix.image_target }}
      platform: ${{ matrix.platform }}
      default-tag: latest
    secrets: inherit
